### PR TITLE
#59 Changed the border and color of dropzone.

### PR DESCRIPTION
**Pull request by Anubhav007**
The UI would like this -
image

@roberto-butti Let me know if something else can be added or changed.

### CODE REVIEW

**Comment by roberto-butti** [comment]
THe border of dropzone was setted as 42b983 as the button.

**Comment by roberto-butti** [comment]
However, I'm trying your proposal , it is great.
So it is ok. The only thing is why:
`  min-height: 150px;
  background: #e3e9f1;
  padding: 20px 20px;`

is in .dropzone instead of #dropzone ?

**Comment by Anubhav007** [comment]
@roberto-butti I changed 42b983 to 6f8c90 to match the changed color of the dropzone. Also i added other styling in .dropzone because if when I adding those in #dropzone, the change of color on hover was not working.

**Comment by Anubhav007** [comment]
We can also change the dropzone color to something like this -
image
Then the dropzone border can be changed back to 42b983

**Comment by roberto-butti** [comment]
> We can also change the dropzone color to something like this -
> image
> Then the dropzone border can be changed back to 42b983

Very good!
What do you think, do you prefer this solution or the previous one?
I think that we could merge the "green" one

**Comment by Anubhav007** [comment]
@roberto-butti Changed to green color

**Pull request merged**
