### PR TITLE
files are now importable from a URL

### PR DESCRIPTION
**Pull request by TobyAsE**
Added a text-field and a button.
To avoid dealing CORS, I had to use the Proxy [cors-anywhere.herokuapp.com](https://cors-anywhere.herokuapp.com/) for getting the file at the URL.

### CODE REVIEW

**Comment by roberto-butti** [comment]
Amazing, thank you @TobyAsE !
I have 3 suggestion:
- I understand the use of "proxy". Why don't you use a sort of .env parameters to store the URL of proxy (on heroku) so the developer that wants customize it (maybe using a his own proxy) can do in a easy way (maybe once we merge this pull request we could open a new issue about moving the URL into a configuration file)
- I have a layout problem with the input text for the URL. I attach a screenshot
Screenshot 2019-10-04 at 21 44 24
- i have some waring by prettier (about src/components/Fit.vue formatting)

What do you think ?

**Comment by TobyAsE** [comment]
The layout problem is fixed, I threw a few bootstrap-classes around.
Of course we can move the proxy-URL somewhere else, good idea to put it in a separate issue once this one is merged.
What do you mean with your last point. Do you mean we should clean up the Fit.vue a bit? Yes, we do. But that is probably also a thing that can be moved to a separate issue.

**Comment by TobyAsE** [comment]
Ah, you meant the linter. This went totally over my head. You learn something new every day I guess... Anyways, should be all fixed now.

**Comment by roberto-butti** [comment]
Ok, THANK YOU!!! 🎉 
We can close #36 
I will open 2 new issues:
- better UI for error messages (url not valid or file upload is not the correct format)
- move the URL of proxy, in a kind of configuration file (.env or something else), just to allow to the developers to customize with a proxy that he own (it is important for privacy reason, the data is sending to 3rd party proxy service)

**Pull request merged**
